#pragma once
#include "ECS.h"
#include "TransformComponent.h"
#include "SpriteComponent.h"
#include "KeyboardController.h"
#include "ColliderComponent.h"
#include "HungerComponent.h"
#include "FoodComponent.h"
#include "DialogtextComponent.h"